# Jekyll settings
#
title: Avec nos partenaires en 2018
email: contact@arboriculteurs-lichtenberg.eu
description: > # this means to ignore newlines until "baseurl:"
  Un reportage sur les activités de l'AALE, animations et prestations auprès de ses partenaires.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://www.arboriculteurs-lichtenberg.eu" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: jekyllrb
github_username:  jekyll
nav_direction: vertical # vertical, horizontal 
image_dir: "assets/images"
sound_dir: "assets/sounds"
sound_source: ""
collections:
    - sections
# Build settings
markdown: kramdown
plugins:
  - github-pages
exclude:
  - Gemfile
  - Gemfile.lock
  - _site
